/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "bit_math.h"
#include "std_types.h"
#include "rcc.h"
#include "NVIC.h"
#include "dio.h"
#include "icu.h"
#include "sysTick.h"
#include "ultrasonic.h"

int main(void)
{
	u16 read;
	rcc_setSystemClk(HSI);
	rcc_enablePeriClk(APB2,TIM8_EN);
	rcc_enablePeriClk(AHB,IOPA_EN);
	rcc_enablePeriClk(AHB,IOPC_EN);


	sysTick_init(AHB_8,NULLPTR);


	Ultrasonic_init();



    /* Loop forever */
	for(;;)
	{
		Ultrasonic_Trigger();
		read = Ultrasonic_readDistance();
		sysTick_start(500000);



	}
}
