/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "bit_math.h"
#include "std_types.h"
#include "rcc.h"
#include "NVIC.h"
#include "dio.h"
#include "icu.h"
#include "sysTick.h"
#include "ultrasonic.h"
#include "pwm.h"

int main(void)
{
	u16 read1,read2;
	rcc_setSystemClk(HSI);
	rcc_enablePeriClk(APB2,TIM8_EN);
	rcc_enablePeriClk(APB2,TIM1_EN);
	rcc_enablePeriClk(APB1,TIM2_EN);


	rcc_enablePeriClk(AHB,IOPA_EN);
	rcc_enablePeriClk(AHB,IOPB_EN);
	rcc_enablePeriClk(AHB,IOPC_EN);


	sysTick_init(AHB_8,(void*)RET_NULLPTR);


	//Ultrasonic_init();

	// A0 F1, A15 F1 , A5 F1

	DIO_setupPinMode( PORTA_ID ,PIN0_ID , PIN_ALTERNATE );
	DIO_setAlternateFunction(PORTA_ID ,PIN0_ID , AF1 );

	PWM_Init();
	PWM_Start(channel1, 0);
	read1 = 1;
	PWM_Start(channel1, 100);
	read1 = 1;


    /* Loop forever */
	for(;;)
	{
//		Ultrasonic_Trigger( TRIGGER4_PORT , TRIGGER4_PIN , UltraSonic_Channel4 );
//		read1 = Ultrasonic_readDistance();
//		sysTick_start(500000);
//
//		Ultrasonic_Trigger( TRIGGER1_PORT , TRIGGER1_PIN , UltraSonic_Channel1 );
//		read2 = Ultrasonic_readDistance();
//		sysTick_start(500000);

		if(read1 !=0)
		{

		}
		if(read2 !=0)
		{

		}

	}
}
